name: Deploy infra
on: [workflow_dispatch]
jobs:
    deploy-infra:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main

            - name: Log into Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Deploy bicep
              uses: azure/arm-deploy@v1
              with:
                scope: resourcegroup
                subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
                template: ./infra/main.bicep