name: Deploy services
on: [workflow_dispatch]
permissions:
    id-token: write
    contents: read
env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 9.0.x
  WORKING_DIRECTORY: .
  AZURE_WEBAPP_YARP_PROXY: proxy-web-service
  AZURE_WEBAPP_NAME_SERVICE_A: web-service-a
  AZURE_WEBAPP_NAME_SERVICE_B: web-service-b
  BASIC_SERVICE_LOCATION: ./code/BasicService
  YARP_PROXY_LOCATION: ./code/YarpProxy
  BASIC_SERVICE_AZURE_WEBAPP_PACKAGE_PATH: ./published/BasicService
  YARP_PROXY_AZURE_WEBAPP_PACKAGE_PATH: ./published/YarpProxy
jobs:
    build_basic_service:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@main

          - name: Setup .NET SDK
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

          - name: Restore
            run: dotnet restore "${{ env.BASIC_SERVICE_LOCATION }}"

          - name: Build
            run: dotnet build "${{ env.BASIC_SERVICE_LOCATION }}" --configuration ${{ env.CONFIGURATION }} --no-restore

          - name: Publish
            run: dotnet publish "${{ env.BASIC_SERVICE_LOCATION }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.BASIC_SERVICE_AZURE_WEBAPP_PACKAGE_PATH }}"

          - name: Publish Artifacts
            uses: actions/upload-artifact@v4
            with:
              name: webapp
              path: ${{ env.BASIC_SERVICE_AZURE_WEBAPP_PACKAGE_PATH }}

    build_yarp_proxy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main

            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

            - name: Restore
              run: dotnet restore "${{ env.YARP_PROXY_LOCATION }}"

            - name: Build
              run: dotnet build "${{ env.YARP_PROXY_LOCATION }}" --configuration ${{ env.CONFIGURATION }} --no-restore

            - name: Publish
              run: dotnet publish "${{ env.YARP_PROXY_LOCATION }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.YARP_PROXY_AZURE_WEBAPP_PACKAGE_PATH }}"

            - name: Publish Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: webapp
                path: ${{ env.YARP_PROXY_AZURE_WEBAPP_PACKAGE_PATH }}

    deploy:
        runs-on: ubuntu-latest
        needs: [build_basic_service, build_yarp_proxy]
        steps:
        - name: Download artifact basic service from build job
          uses: actions/download-artifact@v4
          with:
            name: webapp
            path: ${{ env.BASIC_SERVICE_AZURE_WEBAPP_PACKAGE_PATH }}

        - name: Download artifact basic service from build job
          uses: actions/download-artifact@v4
          with:
            name: webapp
            path: ${{ env.YARP_PROXY_AZURE_WEBAPP_PACKAGE_PATH }}

        - name: Azure Login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Deploy service A
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME_SERVICE_A }}
            package: ${{ env.BASIC_SERVICE_AZURE_WEBAPP_PACKAGE_PATH }}

        - name: Deploy service B
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME_SERVICE_B }}
            package: ${{ env.BASIC_SERVICE_AZURE_WEBAPP_PACKAGE_PATH }}

        - name: Deploy Yarp Proxy
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.AZURE_WEBAPP_YARP_PROXY }}
            package: ${{ env.YARP_PROXY_AZURE_WEBAPP_PACKAGE_PATH }}