name: Deploy services
on: [workflow_dispatch]
permissions:
    id-token: write
    contents: read
env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 9.0.x
  WORKING_DIRECTORY: .
  AZURE_WEBAPP_NAME_SERVICE_A: web-service-a
  AZURE_WEBAPP_NAME_SERVICE_B: web-service-b
  BASIC_SERVICE_LOCATION: ./code/BasicService
  BASIC_SERVICE_AZURE_WEBAPP_PACKAGE_PATH: ./published/BasicService
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main

            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

            - name: Restore
              run: dotnet restore "${{ env.BASIC_SERVICE_LOCATION }}"

            - name: Build
              run: dotnet build "${{ env.BASIC_SERVICE_LOCATION }}" --configuration ${{ env.CONFIGURATION }} --no-restore

            - name: Publish
              run: dotnet publish "${{ env.BASIC_SERVICE_LOCATION }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.BASIC_SERVICE_AZURE_WEBAPP_PACKAGE_PATH }}"

            - name: Publish Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: webapp
                path: ${{ env.BASIC_SERVICE_AZURE_WEBAPP_PACKAGE_PATH }}

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: webapp
            path: ${{ env.BASIC_SERVICE_AZURE_WEBAPP_PACKAGE_PATH }}

        - name: Azure Login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Deploy to Azure WebApp
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME_SERVICE_A }}
            package: ${{ env.BASIC_SERVICE_AZURE_WEBAPP_PACKAGE_PATH }}